name: 💡 Feature Request
description: Have a new idea or feature? Share it with our team.
labels: ['Feature Request']

body:
  - type: textarea
    id: description
    attributes:
      label: Problem to Solve
      description: A clear and concise description of the problem this feature would solve. For example, I am always frustrated when [...].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
