<?php

return [
    [
        'key'    => 'sales.payment_methods.razorpay',
        'name'   => 'razorpay::app.configuration.name',
        'info'   => 'razorpay::app.configuration.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'active',
                'title'         => 'razorpay::app.configuration.status',
                'type'          => 'boolean',
                'validation'    => 'required',
                'channel_based' => false,
                'locale_based'  => false,
            ], [
                'name'          => 'title',
                'title'         => 'razorpay::app.configuration.title',
                'type'          => 'text',
                'validation'    => 'required|max:50',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'description',
                'title'         => 'razorpay::app.configuration.description',
                'type'          => 'textarea',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'sandbox',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type'          => 'boolean',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'test_client_id',
                'title'         => 'razorpay::app.configuration.test-mode-id',
                'type'          => 'text',
                'info'          => 'razorpay::app.configuration.sandbox-only',
                'validation'    => 'max:200',
                'depends'       => 'sandbox:1',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'test_client_secret',
                'title'         => 'razorpay::app.configuration.test-mode-secret',
                'type'          => 'text',
                'info'          => 'razorpay::app.configuration.sandbox-only',
                'depends'       => 'sandbox:1',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'client_id',
                'title'         => 'razorpay::app.configuration.client-id',
                'type'          => 'text',
                'info'          => 'razorpay::app.configuration.production-only',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                 'name'         => 'client_secret',
                'title'         => 'razorpay::app.configuration.client-secret',
                'type'          => 'text',
                'info'          => 'razorpay::app.configuration.production-only',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'merchant_name',
                'title'         => 'razorpay::app.configuration.merchant_name',
                'type'          => 'text',
                'validation'    => 'required',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ], [
                'name'          => 'merchant_desc',
                'title'         => 'razorpay::app.configuration.merchant_desc',
                'type'          => 'textarea',
                'validation'    => 'max:200',
                'channel_based' => false,
                'locale_based'  => true,
            ],
        ],
    ],
];