<?php

namespace Webkul\Installer\Database\Seeders\Attribute;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('attributes')->delete();

        DB::table('attribute_translations')->delete();

        $now = Carbon::now();

        DB::table('attributes')->insert([
            [
                'id'                  => 1,
                'code'                => 'sku',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.sku'),
                'type'                => 'text',
                'validation'          => null,
                'position'            => 1,
                'is_required'         => 1,
                'is_unique'           => 1,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 2,
                'code'                => 'name',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.name'),
                'type'                => 'text',
                'validation'          => null,
                'position'            => 3,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 1,
            ], [
                'id'                  => 3,
                'code'                => 'url_key',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.url-key'),
                'type'                => 'text',
                'validation'          => null,
                'position'            => 4,
                'is_required'         => 1,
                'is_unique'           => 1,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 4,
                'code'                => 'tax_category_id',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.tax-category'),
                'type'                => 'select',
                'validation'          => null,
                'position'            => 5,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 5,
                'code'                => 'new',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.new'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 6,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 6,
                'code'                => 'featured',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.featured'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 7,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 7,
                'code'                => 'visible_individually',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.visible-individually'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 9,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 8,
                'code'                => 'status',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.status'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 10,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 9,
                'code'                => 'short_description',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.short-description'),
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 11,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 10,
                'code'                => 'description',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.description'),
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 12,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 1,
            ], [
                'id'                  => 11,
                'code'                => 'price',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.price'),
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 13,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 1,
            ], [
                'id'                  => 12,
                'code'                => 'cost',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.cost'),
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 14,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 13,
                'code'                => 'special_price',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.special-price'),
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 15,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 14,
                'code'                => 'special_price_from',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.special-price-from'),
                'type'                => 'date',
                'validation'          => null,
                'position'            => 16,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 15,
                'code'                => 'special_price_to',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.special-price-to'),
                'type'                => 'date',
                'validation'          => null,
                'position'            => 17,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 16,
                'code'                => 'meta_title',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.meta-title'),
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 18,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 17,
                'code'                => 'meta_keywords',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.meta-keywords'),
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 20,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 18,
                'code'                => 'meta_description',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.meta-description'),
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 21,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 19,
                'code'                => 'length',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.length'),
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 22,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 20,
                'code'                => 'width',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.width'),
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 23,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 21,
                'code'                => 'height',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.height'),
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 24,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 22,
                'code'                => 'weight',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.weight'),
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 25,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 23,
                'code'                => 'color',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.color'),
                'type'                => 'select',
                'validation'          => null,
                'position'            => 26,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 1,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 24,
                'code'                => 'size',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.size'),
                'type'                => 'select',
                'validation'          => null,
                'position'            => 27,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 1,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 25,
                'code'                => 'brand',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.brand'),
                'type'                => 'select',
                'validation'          => null,
                'position'            => 28,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 1,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 26,
                'code'                => 'guest_checkout',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.guest-checkout'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 8,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 27,
                'code'                => 'product_number',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.product-number'),
                'type'                => 'text',
                'validation'          => null,
                'position'            => 2,
                'is_required'         => 0,
                'is_unique'           => 1,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ], [
                'id'                  => 28,
                'code'                => 'manage_stock',
                'admin_name'          => trans('installer::app.seeders.attribute.attributes.manage-stock'),
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 1,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => 1,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => 0,
            ],
        ]);

        DB::table('attribute_translations')->insert([
            [
                'id'           => 1,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.sku'),
                'attribute_id' => 1,
            ], [
                'id'           => 2,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.name'),
                'attribute_id' => 2,
            ], [
                'id'           => 3,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.url-key'),
                'attribute_id' => 3,
            ], [
                'id'           => 4,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.tax-category'),
                'attribute_id' => 4,
            ], [
                'id'           => 5,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.new'),
                'attribute_id' => 5,
            ], [
                'id'           => 6,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.featured'),
                'attribute_id' => 6,
            ], [
                'id'           => 7,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.visible-individually'),
                'attribute_id' => 7,
            ], [
                'id'           => 8,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.status'),
                'attribute_id' => 8,
            ], [
                'id'           => 9,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.short-description'),
                'attribute_id' => 9,
            ], [
                'id'           => 10,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.description'),
                'attribute_id' => 10,
            ], [
                'id'           => 11,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.price'),
                'attribute_id' => 11,
            ], [
                'id'           => 12,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.cost'),
                'attribute_id' => 12,
            ], [
                'id'           => 13,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.special-price'),
                'attribute_id' => 13,
            ], [
                'id'           => 14,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.special-price-from'),
                'attribute_id' => 14,
            ], [
                'id'           => 15,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.special-price-to'),
                'attribute_id' => 15,
            ], [
                'id'           => 16,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.meta-title'),
                'attribute_id' => 16,
            ], [
                'id'           => 17,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.meta-keywords'),
                'attribute_id' => 17,
            ], [
                'id'           => 18,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.meta-description'),
                'attribute_id' => 18,
            ], [
                'id'           => 19,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.width'),
                'attribute_id' => 19,
            ], [
                'id'           => 20,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.height'),
                'attribute_id' => 20,
            ], [
                'id'           => 21,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.depth'),
                'attribute_id' => 21,
            ], [
                'id'           => 22,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.weight'),
                'attribute_id' => 22,
            ], [
                'id'           => 23,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.color'),
                'attribute_id' => 23,
            ], [
                'id'           => 24,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.size'),
                'attribute_id' => 24,
            ], [
                'id'           => 25,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.brand'),
                'attribute_id' => 25,
            ], [
                'id'           => 26,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.guest-checkout'),
                'attribute_id' => 26,
            ], [
                'id'           => 27,
                'locale'       => config('app.locale'),
                'name'         => trans('installer::app.seeders.attribute.attributes.product-number'),
                'attribute_id' => 27,
            ],
        ]);
    }
}
