[www]
user = www-data
group = www-data

listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 8
pm.max_requests = 500

catch_workers_output = yes
decorate_workers_output = no
clear_env = no

request_terminate_timeout = 300s
