<?php

namespace Webkul\Installer\Database\Seeders\Category;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Http\File;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CategoryTableSeeder extends Seeder
{
    /**
     * Base path for the images.
     */
    const BASE_PATH = 'packages/Webkul/Installer/src/Resources/assets/images/seeders/category/';

    /**
     * Seed the application's database.
     *
     * @param  array  $parameters
     * @return void
     */
    public function run($parameters = [])
    {
        DB::table('categories')->delete();

        DB::table('category_translations')->delete();

        $now = Carbon::now();

        $defaultLocale = $parameters['default_locale'] ?? config('app.locale');

        DB::table('categories')->insert([
            [
                'id' => 1,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                '_lft' => 1,
                '_rgt' => 84,
                'parent_id' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $locales = $parameters['allowed_locales'] ?? [$defaultLocale];

        foreach ($locales as $locale) {
            DB::table('category_translations')->insert([
                [
                    'name' => trans('installer::app.seeders.category.categories.name', [], $locale),
                    'slug' => 'root',
                    'description' => trans('installer::app.seeders.category.categories.description', [], $locale),
                    'meta_title' => '',
                    'meta_description' => '',
                    'meta_keywords' => '',
                    'category_id' => '1',
                    'locale' => $locale,
                ],
            ]);
        }
    }

    /**
     * Create Sample Categories.
     *
     * @return void
     */
    public function sampleCategories(array $parameters = [])
    {
        $defaultLocale = $parameters['default_locale'] ?? config('app.locale');

        $now = Carbon::now();

        $locales = $parameters['allowed_locales'] ?? [$defaultLocale];

        DB::table('categories')->insert([
            [
                'id' => 2,
                'position' => 1,
                'logo_path' => $this->storeFileIfExists('category/2', '2/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 2,
                '_rgt' => 11,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'position' => 3,
                'logo_path' => $this->storeFileIfExists('category/3', '3/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 20,
                '_rgt' => 29,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'position' => 2,
                'logo_path' => $this->storeFileIfExists('category/4', '4/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 12,
                '_rgt' => 19,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 3,
                '_rgt' => 4,
                'parent_id' => 2,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 5,
                '_rgt' => 6,
                'parent_id' => 2,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 7,
                '_rgt' => 8,
                'parent_id' => 2,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 9,
                '_rgt' => 10,
                'parent_id' => 2,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 13,
                '_rgt' => 14,
                'parent_id' => 4,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 15,
                '_rgt' => 16,
                'parent_id' => 4,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 17,
                '_rgt' => 18,
                'parent_id' => 4,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 19,
                '_rgt' => 20,
                'parent_id' => 4,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 21,
                '_rgt' => 22,
                'parent_id' => 3,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 23,
                '_rgt' => 24,
                'parent_id' => 3,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 25,
                '_rgt' => 26,
                'parent_id' => 3,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 27,
                '_rgt' => 28,
                'parent_id' => 3,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'position' => 4,
                'logo_path' => $this->storeFileIfExists('category/17', '17/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 30,
                '_rgt' => 37,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 31,
                '_rgt' => 32,
                'parent_id' => 17,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 33,
                '_rgt' => 34,
                'parent_id' => 17,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 35,
                '_rgt' => 36,
                'parent_id' => 17,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'position' => 5,
                'logo_path' => $this->storeFileIfExists('category/21', '21/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 38,
                '_rgt' => 49,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 39,
                '_rgt' => 40,
                'parent_id' => 21,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 41,
                '_rgt' => 44,
                'parent_id' => 21,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 42,
                '_rgt' => 43,
                'parent_id' => 23,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 45,
                '_rgt' => 46,
                'parent_id' => 21,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 47,
                '_rgt' => 48,
                'parent_id' => 21,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'position' => 6,
                'logo_path' => $this->storeFileIfExists('category/27', '27/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 50,
                '_rgt' => 59,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 51,
                '_rgt' => 52,
                'parent_id' => 27,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 53,
                '_rgt' => 54,
                'parent_id' => 27,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 55,
                '_rgt' => 56,
                'parent_id' => 27,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 57,
                '_rgt' => 58,
                'parent_id' => 27,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'position' => 7,
                'logo_path' => $this->storeFileIfExists('category/32', '32/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 60,
                '_rgt' => 69,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 61,
                '_rgt' => 62,
                'parent_id' => 32,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 63,
                '_rgt' => 64,
                'parent_id' => 32,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 65,
                '_rgt' => 66,
                'parent_id' => 32,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 67,
                '_rgt' => 68,
                'parent_id' => 32,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'position' => 8,
                'logo_path' => $this->storeFileIfExists('category/37', '37/1.webp'),
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 70,
                '_rgt' => 79,
                'parent_id' => 1,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'position' => 1,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 71,
                '_rgt' => 72,
                'parent_id' => 37,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'position' => 2,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 73,
                '_rgt' => 74,
                'parent_id' => 37,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'position' => 3,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 75,
                '_rgt' => 76,
                'parent_id' => 37,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'position' => 4,
                'logo_path' => null,
                'status' => 1,
                'display_mode' => 'products_and_description',
                '_lft' => 77,
                '_rgt' => 78,
                'parent_id' => 37,
                'additional' => null,
                'banner_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        foreach ($locales as $locale) {
            DB::table('category_translations')->insert([
                [
                    'category_id' => 2,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.2.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.2.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.2.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.2.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.2.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.2.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.2.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 3,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.3.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.3.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.3.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.3.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.3.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.3.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.3.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 4,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.4.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.4.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.4.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.4.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.4.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.4.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.4.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 5,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.5.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.5.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.5.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.5.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.5.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.5.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.5.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 6,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.6.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.6.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.6.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.6.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.6.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.6.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.6.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 7,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.7.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.7.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.7.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.7.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.7.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.7.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.7.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 8,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.8.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.8.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.8.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.8.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.8.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.8.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.8.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 9,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.9.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.9.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.9.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.9.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.9.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.9.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.9.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 10,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.10.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.10.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.10.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.10.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.10.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.10.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.10.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 11,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.11.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.11.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.11.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.11.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.11.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.11.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.11.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 12,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.12.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.12.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.12.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.12.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.12.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.12.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.12.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 13,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.13.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.13.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.13.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.13.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.13.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.13.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.13.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 14,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.14.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.14.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.14.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.14.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.14.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.14.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.14.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 15,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.15.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.15.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.15.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.15.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.15.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.15.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.15.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 16,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.16.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.16.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.16.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.16.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.16.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.16.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.16.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 17,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.17.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.17.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.17.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.17.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.17.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.17.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.17.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 18,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.18.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.18.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.18.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.18.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.18.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.18.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.18.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 19,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.19.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.19.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.19.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.19.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.19.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.19.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.19.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 20,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.20.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.20.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.20.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.20.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.20.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.20.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.20.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 21,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.21.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.21.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.21.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.21.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.21.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.21.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.21.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 22,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.22.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.22.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.22.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.22.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.22.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.22.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.22.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 23,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.23.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.23.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.23.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.23.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.23.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.23.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.23.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 24,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.24.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.24.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.24.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.24.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.24.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.24.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.24.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 25,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.25.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.25.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.25.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.25.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.25.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.25.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.25.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 26,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.26.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.26.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.26.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.26.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.26.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.26.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.26.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 27,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.27.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.27.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.27.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.27.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.27.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.27.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.27.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 28,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.28.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.28.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.28.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.28.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.28.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.28.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.28.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 29,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.29.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.29.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.29.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.29.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.29.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.29.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.29.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 30,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.30.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.30.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.30.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.30.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.30.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.30.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.30.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 31,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.31.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.31.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.31.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.31.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.31.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.31.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.31.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 32,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.32.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.32.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.32.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.32.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.32.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.32.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.32.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 33,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.33.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.33.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.33.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.33.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.33.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.33.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.33.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 34,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.34.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.34.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.34.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.34.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.34.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.34.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.34.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 35,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.35.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.35.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.35.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.35.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.35.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.35.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.35.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 36,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.36.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.36.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.36.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.36.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.36.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.36.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.36.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 37,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.37.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.37.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.37.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.37.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.37.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.37.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.37.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 38,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.38.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.38.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.38.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.38.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.38.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.38.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.38.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 39,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.39.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.39.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.39.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.39.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.39.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.39.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.39.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 40,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.40.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.40.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.40.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.40.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.40.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.40.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.40.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
                [
                    'category_id' => 41,
                    'name' => trans('installer::app.seeders.sample-categories.category-translation.41.name', [], $locale),
                    'slug' => trans('installer::app.seeders.sample-categories.category-translation.41.slug', [], $locale),
                    'url_path' => trans('installer::app.seeders.sample-categories.category-translation.41.url-path', [], $locale),
                    'description' => trans('installer::app.seeders.sample-categories.category-translation.41.description', [], $locale),
                    'meta_title' => trans('installer::app.seeders.sample-categories.category-translation.41.meta-title', [], $locale),
                    'meta_description' => trans('installer::app.seeders.sample-categories.category-translation.41.meta-description', [], $locale),
                    'meta_keywords' => trans('installer::app.seeders.sample-categories.category-translation.41.meta-keywords', [], $locale),
                    'locale_id' => null,
                    'locale' => $locale,
                ],
            ]);
        }

        DB::table('category_filterable_attributes')->insert([
            ['category_id' => 2, 'attribute_id' => 11],
            ['category_id' => 2, 'attribute_id' => 23],
            ['category_id' => 2, 'attribute_id' => 24],
            ['category_id' => 2, 'attribute_id' => 25],
            ['category_id' => 3, 'attribute_id' => 11],
            ['category_id' => 3, 'attribute_id' => 23],
            ['category_id' => 3, 'attribute_id' => 24],
            ['category_id' => 3, 'attribute_id' => 25],
            ['category_id' => 4, 'attribute_id' => 11],
            ['category_id' => 4, 'attribute_id' => 23],
            ['category_id' => 4, 'attribute_id' => 24],
            ['category_id' => 4, 'attribute_id' => 25],
            ['category_id' => 5, 'attribute_id' => 11],
            ['category_id' => 5, 'attribute_id' => 23],
            ['category_id' => 5, 'attribute_id' => 24],
            ['category_id' => 5, 'attribute_id' => 25],
            ['category_id' => 6, 'attribute_id' => 11],
            ['category_id' => 6, 'attribute_id' => 23],
            ['category_id' => 6, 'attribute_id' => 24],
            ['category_id' => 6, 'attribute_id' => 25],
            ['category_id' => 7, 'attribute_id' => 11],
            ['category_id' => 7, 'attribute_id' => 23],
            ['category_id' => 7, 'attribute_id' => 24],
            ['category_id' => 7, 'attribute_id' => 25],
            ['category_id' => 8, 'attribute_id' => 11],
            ['category_id' => 8, 'attribute_id' => 23],
            ['category_id' => 8, 'attribute_id' => 24],
            ['category_id' => 8, 'attribute_id' => 25],
            ['category_id' => 9, 'attribute_id' => 11],
            ['category_id' => 9, 'attribute_id' => 23],
            ['category_id' => 9, 'attribute_id' => 24],
            ['category_id' => 9, 'attribute_id' => 25],
            ['category_id' => 10, 'attribute_id' => 11],
            ['category_id' => 10, 'attribute_id' => 23],
            ['category_id' => 10, 'attribute_id' => 24],
            ['category_id' => 10, 'attribute_id' => 25],
            ['category_id' => 11, 'attribute_id' => 11],
            ['category_id' => 11, 'attribute_id' => 23],
            ['category_id' => 11, 'attribute_id' => 24],
            ['category_id' => 11, 'attribute_id' => 25],
            ['category_id' => 12, 'attribute_id' => 11],
            ['category_id' => 12, 'attribute_id' => 23],
            ['category_id' => 12, 'attribute_id' => 24],
            ['category_id' => 12, 'attribute_id' => 25],
            ['category_id' => 13, 'attribute_id' => 11],
            ['category_id' => 13, 'attribute_id' => 23],
            ['category_id' => 13, 'attribute_id' => 24],
            ['category_id' => 13, 'attribute_id' => 25],
            ['category_id' => 14, 'attribute_id' => 11],
            ['category_id' => 14, 'attribute_id' => 23],
            ['category_id' => 14, 'attribute_id' => 24],
            ['category_id' => 14, 'attribute_id' => 25],
            ['category_id' => 15, 'attribute_id' => 11],
            ['category_id' => 15, 'attribute_id' => 23],
            ['category_id' => 15, 'attribute_id' => 24],
            ['category_id' => 15, 'attribute_id' => 25],
            ['category_id' => 16, 'attribute_id' => 11],
            ['category_id' => 16, 'attribute_id' => 23],
            ['category_id' => 16, 'attribute_id' => 24],
            ['category_id' => 16, 'attribute_id' => 25],
            ['category_id' => 17, 'attribute_id' => 11],
            ['category_id' => 17, 'attribute_id' => 23],
            ['category_id' => 17, 'attribute_id' => 24],
            ['category_id' => 17, 'attribute_id' => 25],
            ['category_id' => 18, 'attribute_id' => 11],
            ['category_id' => 18, 'attribute_id' => 23],
            ['category_id' => 18, 'attribute_id' => 24],
            ['category_id' => 18, 'attribute_id' => 25],
            ['category_id' => 19, 'attribute_id' => 11],
            ['category_id' => 20, 'attribute_id' => 11],
            ['category_id' => 21, 'attribute_id' => 11],
            ['category_id' => 22, 'attribute_id' => 11],
            ['category_id' => 23, 'attribute_id' => 11],
            ['category_id' => 24, 'attribute_id' => 11],
            ['category_id' => 25, 'attribute_id' => 11],
            ['category_id' => 26, 'attribute_id' => 11],
            ['category_id' => 27, 'attribute_id' => 11],
            ['category_id' => 27, 'attribute_id' => 23],
            ['category_id' => 27, 'attribute_id' => 24],
            ['category_id' => 27, 'attribute_id' => 25],
            ['category_id' => 28, 'attribute_id' => 11],
            ['category_id' => 28, 'attribute_id' => 23],
            ['category_id' => 28, 'attribute_id' => 24],
            ['category_id' => 28, 'attribute_id' => 25],
            ['category_id' => 29, 'attribute_id' => 11],
            ['category_id' => 29, 'attribute_id' => 23],
            ['category_id' => 29, 'attribute_id' => 24],
            ['category_id' => 29, 'attribute_id' => 25],
            ['category_id' => 30, 'attribute_id' => 11],
            ['category_id' => 30, 'attribute_id' => 23],
            ['category_id' => 30, 'attribute_id' => 24],
            ['category_id' => 31, 'attribute_id' => 11],
            ['category_id' => 31, 'attribute_id' => 23],
            ['category_id' => 31, 'attribute_id' => 24],
            ['category_id' => 31, 'attribute_id' => 25],
            ['category_id' => 32, 'attribute_id' => 11],
            ['category_id' => 32, 'attribute_id' => 23],
            ['category_id' => 32, 'attribute_id' => 24],
            ['category_id' => 32, 'attribute_id' => 25],
            ['category_id' => 33, 'attribute_id' => 11],
            ['category_id' => 33, 'attribute_id' => 23],
            ['category_id' => 33, 'attribute_id' => 24],
            ['category_id' => 33, 'attribute_id' => 25],
            ['category_id' => 34, 'attribute_id' => 11],
            ['category_id' => 34, 'attribute_id' => 23],
            ['category_id' => 34, 'attribute_id' => 24],
            ['category_id' => 34, 'attribute_id' => 25],
            ['category_id' => 35, 'attribute_id' => 11],
            ['category_id' => 35, 'attribute_id' => 23],
            ['category_id' => 35, 'attribute_id' => 24],
            ['category_id' => 35, 'attribute_id' => 25],
            ['category_id' => 36, 'attribute_id' => 11],
            ['category_id' => 36, 'attribute_id' => 23],
            ['category_id' => 36, 'attribute_id' => 24],
            ['category_id' => 36, 'attribute_id' => 25],
            ['category_id' => 37, 'attribute_id' => 11],
            ['category_id' => 37, 'attribute_id' => 23],
            ['category_id' => 37, 'attribute_id' => 24],
            ['category_id' => 37, 'attribute_id' => 25],
            ['category_id' => 38, 'attribute_id' => 11],
            ['category_id' => 38, 'attribute_id' => 23],
            ['category_id' => 38, 'attribute_id' => 24],
            ['category_id' => 38, 'attribute_id' => 25],
            ['category_id' => 39, 'attribute_id' => 11],
            ['category_id' => 39, 'attribute_id' => 23],
            ['category_id' => 39, 'attribute_id' => 24],
            ['category_id' => 39, 'attribute_id' => 25],
            ['category_id' => 40, 'attribute_id' => 11],
            ['category_id' => 40, 'attribute_id' => 23],
            ['category_id' => 40, 'attribute_id' => 24],
            ['category_id' => 40, 'attribute_id' => 25],
            ['category_id' => 41, 'attribute_id' => 11],
            ['category_id' => 41, 'attribute_id' => 23],
            ['category_id' => 41, 'attribute_id' => 24],
            ['category_id' => 41, 'attribute_id' => 25],
        ]);
    }

    /**
     * Store image in storage.
     *
     * @param  string  $targetPath
     * @param  string  $file
     * @return string|null
     */
    public function storeFileIfExists($targetPath, $file)
    {
        if (file_exists(base_path(self::BASE_PATH.$file))) {
            return 'storage/'.Storage::putFile($targetPath, new File(base_path(self::BASE_PATH.$file)));
        }

        return null;
    }
}
