<?php

return [
    [
        'key' => 'dashboard',
        'name' => 'Dashboard',
        'route' => 'admin.dashboard.index',
        'sort' => 1,
        'icon-class' => 'dashboard-icon',
    ], [
        'key' => 'sales',
        'name' => 'Sales',
        'route' => 'admin.sales.orders.index',
        'sort' => 2,
        'icon-class' => 'sales-icon',
    ], [
        'key' => 'sales.orders',
        'name' => 'Orders',
        'route' => 'admin.sales.orders.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'sales.shipments',
        'name' => 'Shipments',
        'route' => 'admin.sales.shipments.index',
        'sort' => 2,
        'icon-class' => '',
    ], [
        'key' => 'sales.invoices',
        'name' => 'Invoices',
        'route' => 'admin.sales.invoices.index',
        'sort' => 3,
        'icon-class' => '',
    ],
    [
        'key' => 'catalog',
        'name' => 'Catalog',
        'route' => 'admin.catalog.products.index',
        'sort' => 3,
        'icon-class' => 'catalog-icon',
    ], [
        'key' => 'catalog.products',
        'name' => 'Products',
        'route' => 'admin.catalog.products.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'catalog.categories',
        'name' => 'Categories',
        'route' => 'admin.catalog.categories.index',
        'sort' => 2,
        'icon-class' => '',
    ], [
        'key' => 'catalog.attributes',
        'name' => 'Attributes',
        'route' => 'admin.catalog.attributes.index',
        'sort' => 3,
        'icon-class' => '',
    ], [
        'key' => 'catalog.families',
        'name' => 'Families',
        'route' => 'admin.catalog.families.index',
        'sort' => 4,
        'icon-class' => '',
    ], [
        'key' => 'customers',
        'name' => 'Customers',
        'route' => 'admin.customer.index',
        'sort' => 4,
        'icon-class' => 'customer-icon',
    ], [
        'key' => 'customers.customers',
        'name' => 'Customers',
        'route' => 'admin.customer.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'customers.groups',
        'name' => 'Groups',
        'route' => 'admin.groups.index',
        'sort' => 2,
        'icon-class' => '',
    ], [
        'key' => 'customers.reviews',
        'name' => 'Reviews',
        'route' => 'admin.customer.review.index',
        'sort' => 3,
        'icon-class' => '',
    ], [
        'key' => 'customers.subscribers',
        'name' => 'Newsletter Subscription',
        'route' => 'admin.customers.subscribers.index',
        'sort' => 4,
        'icon-class' => '',
    ], [
        'key' => 'configuration',
        'name' => 'Configure',
        'route' => 'admin.configuration.index',
        'sort' => 5,
        'icon-class' => 'configuration-icon',
    ], [
        'key' => 'settings',
        'name' => 'Settings',
        'route' => 'admin.locales.index',
        'sort' => 6,
        'icon-class' => 'settings-icon',
    ], [
        'key' => 'settings.locales',
        'name' => 'Locales',
        'route' => 'admin.locales.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'settings.currencies',
        'name' => 'Currencies',
        'route' => 'admin.currencies.index',
        'sort' => 2,
        'icon-class' => '',
    ], [
        'key' => 'settings.exchange_rates',
        'name' => 'Exchange Rates',
        'route' => 'admin.exchange_rates.index',
        'sort' => 3,
        'icon-class' => '',
    ], [
        'key' => 'settings.inventory_sources',
        'name' => 'Inventory Sources',
        'route' => 'admin.inventory_sources.index',
        'sort' => 4,
        'icon-class' => '',
    ], [
        'key' => 'settings.channels',
        'name' => 'Channels',
        'route' => 'admin.channels.index',
        'sort' => 5,
        'icon-class' => '',
    ], [
        'key' => 'settings.users',
        'name' => 'Users',
        'route' => 'admin.users.index',
        'sort' => 6,
        'icon-class' => '',
    ], [
        'key' => 'settings.users.users',
        'name' => 'Users',
        'route' => 'admin.users.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'settings.users.roles',
        'name' => 'Roles',
        'route' => 'admin.roles.index',
        'sort' => 2,
        'icon-class' => '',
    ], [
        'key' => 'settings.sliders',
        'name' => 'Sliders',
        'route' => 'admin.sliders.index',
        'sort' => 7,
        'icon-class' => '',
    ], [
        'key' => 'settings.taxes',
        'name' => 'Taxes',
        'route' => 'admin.tax-categories.index',
        'sort' => 8,
        'icon-class' => '',
    ], [
        'key' => 'settings.taxes.tax-categories',
        'name' => 'Tax Categories',
        'route' => 'admin.tax-categories.index',
        'sort' => 1,
        'icon-class' => '',
    ], [
        'key' => 'settings.taxes.tax-rates',
        'name' => 'Tax Rates',
        'route' => 'admin.tax-rates.index',
        'sort' => 2,
        'icon-class' => '',
    ]
];
