docRoot                   $VH_ROOT/public
enableGzip                1

index  {
  useServer               0
  indexFiles              index.php
  autoIndex               0
}

errorlog $SERVER_ROOT/logs/$VH_NAME.error.log {
  useServer               0
  logLevel                INFO
  rollingSize             10M
}

accesslog $SERVER_ROOT/logs/$VH_NAME.access.log {
  useServer               0
  rollingSize             10M
  keepDays                30
}

scripthandler {
  add                     lsapi:lsphp php
}

rewrite  {
  enable                  1
  autoLoadHtaccess        0
  rules                   <<<END_rules
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php [L]
END_rules
}

context / {
  allowBrowse             1
  addDefaultCharset       off

  extraHeaders            <<<END_headers
X-Frame-Options SAMEORIGIN
X-Content-Type-Options nosniff
Referrer-Policy strict-origin-when-cross-origin
END_headers
}

context /.well-known/ {
  allowBrowse             1
}
