name: Deploy to Production

on:
  push:
    branches:
      - 2.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.61.9.43
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/anetea
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache